#!/bin/bash

if [ ! -f ./dist/build/compile_to_llvm/compile_to_llvm ]
then
    echo "Could not find the proper executable. Did you run \"make\"?"
    exit 1
fi

FULL_PATH=$1

if [ -z ${FULL_PATH} ]
then
    echo "Usage: $0 INPUT_FILE"
    exit 1
fi

NAME_WITH_EXTENSION=${FULL_PATH##*/}
NAME=${NAME_WITH_EXTENSION%%.*}
DIRECTORY=${FULL_PATH%${NAME_WITH_EXTENSION}}
if [ -z ${DIRECTORY} ]
then
    DIRECTORY=./
fi
LL_PATH="${DIRECTORY}${NAME}.ll"
BC_PATH="${DIRECTORY}${NAME}.bc"

set -e
./dist/build/compile_to_llvm/compile_to_llvm ${FULL_PATH} >${LL_PATH}
llvm-as ${LL_PATH} -o ${BC_PATH}

