#!/bin/bash

if [ ! -f ./dist/build/compile_to_jvm/compile_to_jvm ]
then
    echo "Could not find the proper executable. Did you run \"make\"?"
    exit 1
fi

FULL_PATH=$1

if [ -z ${FULL_PATH} ]
then
    echo "Usage: $0 INPUT_FILE"
    exit 1
fi

NAME_WITH_EXTENSION=${FULL_PATH##*/}
NAME=${NAME_WITH_EXTENSION%%.*}
DIRECTORY=${FULL_PATH%${NAME_WITH_EXTENSION}}
if [ -z ${DIRECTORY} ]
then
    DIRECTORY=./
fi
JASMIN_PATH="${DIRECTORY}${NAME}.j"

set -e
./dist/build/compile_to_jvm/compile_to_jvm ${FULL_PATH} >${JASMIN_PATH}
java -jar ./lib/jasmin.jar -d ${DIRECTORY} ${JASMIN_PATH} >/dev/null

